LOAD DATA
INFILE '/tmp/ydata/ydata.csv'
replace INTO TABLE ydata
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
tkr    CHAR             NULLIF (tkr=BLANKS)
,ydate DATE "YYYY-MM-DD" NULLIF (ydate=BLANKS)
,opn   DECIMAL EXTERNAL NULLIF (opn=BLANKS)
,mx    DECIMAL EXTERNAL NULLIF (mx=BLANKS)
,mn    DECIMAL EXTERNAL NULLIF (mn=BLANKS)
,closing_price  DECIMAL EXTERNAL NULLIF (closing_price=BLANKS)
,vol     DECIMAL EXTERNAL NULLIF (vol=BLANKS)
,adjclse DECIMAL EXTERNAL NULLIF (adjclse=BLANKS)
)
